runtime: nodejs18  # Update with your Node.js version
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.6
env_variables:
  VARIABLE_NAME: "Value"
